// tslint:disable
/**
 * Lethean Binary API
 * Functionality to simplify using LTHN
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpQuery, throwIfNullOrUndefined, OperationOpts, RawAjaxResponse } from '../runtime';

export interface StartLetheandRequest {
    dataDir: string;
    version?: boolean;
}

/**
 * no description
 */
export class VpnApi extends BaseAPI {

    /**
     */
    startLetheand({ dataDir, version }: StartLetheandRequest): Observable<void>
    startLetheand({ dataDir, version }: StartLetheandRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    startLetheand({ dataDir, version }: StartLetheandRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        throwIfNullOrUndefined(dataDir, 'dataDir', 'startLetheand');

        const query: HttpQuery = { // required parameters are used directly since they are already checked by throwIfNullOrUndefined
            'data_dir': dataDir,
        };

        if (version != null) { query['version'] = version; }

        return this.request<void>({
            url: '/letheand/start',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

}
